### PR TITLE
Storage presets display update

### PR DESCRIPTION
**Pull request by jaching**
Implementing changes to persistent storage, display behavior, and adding presets as outline in https://github.com/bkshepherd/DaisySeedProjects/issues/13.

### CODE REVIEW

**Comment by bkshepherd** [comment]
I was just testing this out.  I don't think it's loading the default parameters correctly for FX.  At least it isn't on the tremolo effect.  When I try to load that effect and enable it, both lights are just on.  It's not until I turn the 1st and 2nd knob to change the rate that is starts to pulse the led.  This implies to me that it it didn't properly load the default settings for the parameters.  

I also ran into an issue where if I turn knob 5 (2nd row bottom knob) on the tremolo effect to the Poly Sqr wave shape the tremolo effect is then locked up.

Seems like something isn't working as expected, or is there something that needs to be updated with the tremolo effect to make it work properly with the new preset saving?

**Comment by jaching** [comment]
On loading parameters, I believe I already know the root cause ( I tried simplify the code in PersistentStorage, but this did not remove much assembly code and is wrong in the case of default values), so this will hopefully be as simple as reverting the code in Persistent Storage.

For binned values causing a crash, I will look into this further.

**Comment by jaching** [comment]
As I suspected, the default value was because I was trying to be fancy and assume that we could always use SetParameterRaw (rather than convert to float and call SetFloat), while this is possible with most of the functions in setting persistent storage values, the default case still needs to explicitly be converted.

Here is what the default storage looks like with the changes (storage +44 is Depth (74.0 on IEEE Calculator, Freq is the next word 67.0 on IEE Calculator), so I believe this commit should hopefully fix that issue on your end.
```
(gdb) x/40wx storage.default_settings_.globalEffectsSettings
0x2400a5d8 <storage+28>:        0x00000020      0x00000001      0x00000005      0x00000000
0x2400a5e8 <storage+44>:        0x42940000      0x42860000      0x00000000      0x41400000
0x2400a5f8 <storage+60>:        0x00000001      0x00000002      0x42640000      0x42200000
0x2400a608 <storage+76>:        0x00000001      0x00000004      0x42fe0000      0x00000000
0x2400a618 <storage+92>:        0x41400000      0x00000000      0x00000001      0x0000000d
0x2400a628 <storage+108>:       0x00000000      0x00000000      0x00000000      0x00000000
0x2400a638 <storage+124>:       0x00000000      0x00000000      0x00000000      0x00000000
0x2400a648 <storage+140>:       0x00000000      0x00000000      0x00000000      0x00000000
0x2400a658 <storage+156>:       0x00000000      0x00000000      0x00000000      0x00000000
0x2400a668 <storage+172>:       0x00000000      0x00000000      0x00000000      0x00000000
```


However, despite my best efforts, I am not able to recreate this crash when changing Knob 5 to Poly Blep Square (or any value really).  Can you give me some more details on how you were able to get a crash so I can dive further?

**Comment by jaching** [comment]
Or better, do you have a debugger?  If so, can you recreate the crash scenario and share the backtrace with me?

Either way, I have committed the latest version with the previously mentioned changes.

**Comment by bkshepherd** [comment]
Great! I’ll take a look in a bit.  BTW, not sure if you are in the Electro Smith Daisy discord server, but I’m on there as bkshepherd.  Might be easier to communicate that way for any back and forth

**Comment by jaching** [comment]
I am on there now as Transient, feel free to reach out if there are any issues/updates!

**Pull request merged**
